[package]
name = "presenced-popup"
version = "0.2.0"
description = "Niri Sync Discord - Personal Linux Desktop Companion"
edition = "2021"

[lib]
name = "presenced_popup_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
